package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * CasoSoporte generated by hbm2java
 */
public class CasoSoporte  implements java.io.Serializable {


     private Integer casoId;
     private Proyecto proyecto;
     private Usuario usuario;
     private String tituloCaso;
     private String descripcionCaso;
     private Set<SeguimientoCaso> seguimientoCasos = new HashSet<SeguimientoCaso>(0);

    public CasoSoporte() {
    }

	
    public CasoSoporte(Integer casoId, Proyecto proyecto, Usuario usuario, String tituloCaso, String descripcionCaso) {
        this.casoId = casoId;
        this.proyecto = proyecto;
        this.usuario = usuario;
        this.tituloCaso = tituloCaso;
        this.descripcionCaso = descripcionCaso;
    }
    public CasoSoporte(Integer casoId, Proyecto proyecto, Usuario usuario, String tituloCaso, String descripcionCaso, Set<SeguimientoCaso> seguimientoCasos) {
       this.casoId = casoId;
       this.proyecto = proyecto;
       this.usuario = usuario;
       this.tituloCaso = tituloCaso;
       this.descripcionCaso = descripcionCaso;
       this.seguimientoCasos = seguimientoCasos;
    }
   
    public Integer getCasoId() {
        return this.casoId;
    }
    
    public void setCasoId(Integer casoId) {
        this.casoId = casoId;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTituloCaso() {
        return this.tituloCaso;
    }
    
    public void setTituloCaso(String tituloCaso) {
        this.tituloCaso = tituloCaso;
    }
    public String getDescripcionCaso() {
        return this.descripcionCaso;
    }
    
    public void setDescripcionCaso(String descripcionCaso) {
        this.descripcionCaso = descripcionCaso;
    }
    public Set<SeguimientoCaso> getSeguimientoCasos() {
        return this.seguimientoCasos;
    }
    
    public void setSeguimientoCasos(Set<SeguimientoCaso> seguimientoCasos) {
        this.seguimientoCasos = seguimientoCasos;
    }




}


