package com.dsdsoft.sgp.modelo;
// Generated 28/05/2017 09:42:05 PM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer ciudId;
     private Departamento departamento;
     private String nombreCiudad;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Ciudad() {
    }

	
    public Ciudad(Integer ciudId, Departamento departamento, String nombreCiudad) {
        this.ciudId = ciudId;
        this.departamento = departamento;
        this.nombreCiudad = nombreCiudad;
    }
    public Ciudad(Integer ciudId, Departamento departamento, String nombreCiudad, Set<Cliente> clientes) {
       this.ciudId = ciudId;
       this.departamento = departamento;
       this.nombreCiudad = nombreCiudad;
       this.clientes = clientes;
    }
   
    public Integer getCiudId() {
        return this.ciudId;
    }
    
    public void setCiudId(Integer ciudId) {
        this.ciudId = ciudId;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


