package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clieId;
     private String nombreEmpresa;
     private String nit;
     private String telefonoContacto;
     private String direccionContacto;
     private String nombreContacto;
     private String celularContacto;
     private String enlaceWeb;
     private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

    public Cliente() {
    }

	
    public Cliente(Integer clieId, String telefonoContacto, String nombreContacto, String celularContacto) {
        this.clieId = clieId;
        this.telefonoContacto = telefonoContacto;
        this.nombreContacto = nombreContacto;
        this.celularContacto = celularContacto;
    }
    public Cliente(Integer clieId, String nombreEmpresa, String nit, String telefonoContacto, String direccionContacto, String nombreContacto, String celularContacto, String enlaceWeb, Set<Proyecto> proyectos) {
       this.clieId = clieId;
       this.nombreEmpresa = nombreEmpresa;
       this.nit = nit;
       this.telefonoContacto = telefonoContacto;
       this.direccionContacto = direccionContacto;
       this.nombreContacto = nombreContacto;
       this.celularContacto = celularContacto;
       this.enlaceWeb = enlaceWeb;
       this.proyectos = proyectos;
    }
   
    public Integer getClieId() {
        return this.clieId;
    }
    
    public void setClieId(Integer clieId) {
        this.clieId = clieId;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getTelefonoContacto() {
        return this.telefonoContacto;
    }
    
    public void setTelefonoContacto(String telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }
    public String getDireccionContacto() {
        return this.direccionContacto;
    }
    
    public void setDireccionContacto(String direccionContacto) {
        this.direccionContacto = direccionContacto;
    }
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }
    public String getCelularContacto() {
        return this.celularContacto;
    }
    
    public void setCelularContacto(String celularContacto) {
        this.celularContacto = celularContacto;
    }
    public String getEnlaceWeb() {
        return this.enlaceWeb;
    }
    
    public void setEnlaceWeb(String enlaceWeb) {
        this.enlaceWeb = enlaceWeb;
    }
    public Set<Proyecto> getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }




}


