package com.dsdsoft.sgp.modelo;
// Generated 28/05/2017 09:42:05 PM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer depaId;
     private Pais pais;
     private String nombreDepartamento;
     private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);

    public Departamento() {
    }

	
    public Departamento(Integer depaId, Pais pais, String nombreDepartamento) {
        this.depaId = depaId;
        this.pais = pais;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(Integer depaId, Pais pais, String nombreDepartamento, Set<Ciudad> ciudads) {
       this.depaId = depaId;
       this.pais = pais;
       this.nombreDepartamento = nombreDepartamento;
       this.ciudads = ciudads;
    }
   
    public Integer getDepaId() {
        return this.depaId;
    }
    
    public void setDepaId(Integer depaId) {
        this.depaId = depaId;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set<Ciudad> getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set<Ciudad> ciudads) {
        this.ciudads = ciudads;
    }




}


