package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoHistoriaUsuario generated by hbm2java
 */
public class EstadoHistoriaUsuario  implements java.io.Serializable {


     private Integer eshiId;
     private String descripcionEstado;
     private String nombreCorto;
     private Set<HistoriaDeUsuario> historiaDeUsuarios = new HashSet<HistoriaDeUsuario>(0);

    public EstadoHistoriaUsuario() {
    }

	
    public EstadoHistoriaUsuario(Integer eshiId, String descripcionEstado, String nombreCorto) {
        this.eshiId = eshiId;
        this.descripcionEstado = descripcionEstado;
        this.nombreCorto = nombreCorto;
    }
    public EstadoHistoriaUsuario(Integer eshiId, String descripcionEstado, String nombreCorto, Set<HistoriaDeUsuario> historiaDeUsuarios) {
       this.eshiId = eshiId;
       this.descripcionEstado = descripcionEstado;
       this.nombreCorto = nombreCorto;
       this.historiaDeUsuarios = historiaDeUsuarios;
    }
   
    public Integer getEshiId() {
        return this.eshiId;
    }
    
    public void setEshiId(Integer eshiId) {
        this.eshiId = eshiId;
    }
    public String getDescripcionEstado() {
        return this.descripcionEstado;
    }
    
    public void setDescripcionEstado(String descripcionEstado) {
        this.descripcionEstado = descripcionEstado;
    }
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    public Set<HistoriaDeUsuario> getHistoriaDeUsuarios() {
        return this.historiaDeUsuarios;
    }
    
    public void setHistoriaDeUsuarios(Set<HistoriaDeUsuario> historiaDeUsuarios) {
        this.historiaDeUsuarios = historiaDeUsuarios;
    }




}


