package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoProyecto generated by hbm2java
 */
public class EstadoProyecto  implements java.io.Serializable {


     private Integer esprId;
     private String descripcionEstado;
     private String nombreCorto;
     private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

    public EstadoProyecto() {
    }

	
    public EstadoProyecto(Integer esprId, String descripcionEstado, String nombreCorto) {
        this.esprId = esprId;
        this.descripcionEstado = descripcionEstado;
        this.nombreCorto = nombreCorto;
    }
    public EstadoProyecto(Integer esprId, String descripcionEstado, String nombreCorto, Set<Proyecto> proyectos) {
       this.esprId = esprId;
       this.descripcionEstado = descripcionEstado;
       this.nombreCorto = nombreCorto;
       this.proyectos = proyectos;
    }
   
    public Integer getEsprId() {
        return this.esprId;
    }
    
    public void setEsprId(Integer esprId) {
        this.esprId = esprId;
    }
    public String getDescripcionEstado() {
        return this.descripcionEstado;
    }
    
    public void setDescripcionEstado(String descripcionEstado) {
        this.descripcionEstado = descripcionEstado;
    }
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    public Set<Proyecto> getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }




}


