package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0



/**
 * HistoriaDeUsuario generated by hbm2java
 */
public class HistoriaDeUsuario  implements java.io.Serializable {


     private Integer hiusId;
     private Usuario usuario;
     private Requerimiento requerimiento;
     private EstadoHistoriaUsuario estadoHistoriaUsuario;
     private String detalleHistoria;
     private String tituloHistoria;

    public HistoriaDeUsuario() {
    }

    public HistoriaDeUsuario(Integer hiusId, Usuario usuario, Requerimiento requerimiento, EstadoHistoriaUsuario estadoHistoriaUsuario, String detalleHistoria, String tituloHistoria) {
       this.hiusId = hiusId;
       this.usuario = usuario;
       this.requerimiento = requerimiento;
       this.estadoHistoriaUsuario = estadoHistoriaUsuario;
       this.detalleHistoria = detalleHistoria;
       this.tituloHistoria = tituloHistoria;
    }
   
    public Integer getHiusId() {
        return this.hiusId;
    }
    
    public void setHiusId(Integer hiusId) {
        this.hiusId = hiusId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Requerimiento getRequerimiento() {
        return this.requerimiento;
    }
    
    public void setRequerimiento(Requerimiento requerimiento) {
        this.requerimiento = requerimiento;
    }
    public EstadoHistoriaUsuario getEstadoHistoriaUsuario() {
        return this.estadoHistoriaUsuario;
    }
    
    public void setEstadoHistoriaUsuario(EstadoHistoriaUsuario estadoHistoriaUsuario) {
        this.estadoHistoriaUsuario = estadoHistoriaUsuario;
    }
    public String getDetalleHistoria() {
        return this.detalleHistoria;
    }
    
    public void setDetalleHistoria(String detalleHistoria) {
        this.detalleHistoria = detalleHistoria;
    }
    public String getTituloHistoria() {
        return this.tituloHistoria;
    }
    
    public void setTituloHistoria(String tituloHistoria) {
        this.tituloHistoria = tituloHistoria;
    }




}


