package com.dsdsoft.sgp.modelo;
// Generated 28/05/2017 09:42:05 PM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer paisId;
     private String nombrePais;
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);

    public Pais() {
    }

	
    public Pais(Integer paisId, String nombrePais) {
        this.paisId = paisId;
        this.nombrePais = nombrePais;
    }
    public Pais(Integer paisId, String nombrePais, Set<Departamento> departamentos) {
       this.paisId = paisId;
       this.nombrePais = nombrePais;
       this.departamentos = departamentos;
    }
   
    public Integer getPaisId() {
        return this.paisId;
    }
    
    public void setPaisId(Integer paisId) {
        this.paisId = paisId;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }




}


