package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0



/**
 * ProyectoUsuarioRolId generated by hbm2java
 */
public class ProyectoUsuarioRolId  implements java.io.Serializable {


     private Long usuaId;
     private Long proyId;

    public ProyectoUsuarioRolId() {
    }

    public ProyectoUsuarioRolId(Long usuaId, Long proyId) {
       this.usuaId = usuaId;
       this.proyId = proyId;
    }
   
    public Long getUsuaId() {
        return this.usuaId;
    }
    
    public void setUsuaId(Long usuaId) {
        this.usuaId = usuaId;
    }
    public Long getProyId() {
        return this.proyId;
    }
    
    public void setProyId(Long proyId) {
        this.proyId = proyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProyectoUsuarioRolId) ) return false;
		 ProyectoUsuarioRolId castOther = ( ProyectoUsuarioRolId ) other; 
         
		 return ( (this.getUsuaId()==castOther.getUsuaId()) || ( this.getUsuaId()!=null && castOther.getUsuaId()!=null && this.getUsuaId().equals(castOther.getUsuaId()) ) )
 && ( (this.getProyId()==castOther.getProyId()) || ( this.getProyId()!=null && castOther.getProyId()!=null && this.getProyId().equals(castOther.getProyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuaId() == null ? 0 : this.getUsuaId().hashCode() );
         result = 37 * result + ( getProyId() == null ? 0 : this.getProyId().hashCode() );
         return result;
   }   


}


