package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0



/**
 * ProyectoUsuarioRol generated by hbm2java
 */
public class ProyectoUsuarioRol  implements java.io.Serializable {


     private ProyectoUsuarioRolId id;
     private Proyecto proyecto;
     private Usuario usuario;
     private Rol rol;

    public ProyectoUsuarioRol() {
    }

    public ProyectoUsuarioRol(ProyectoUsuarioRolId id, Proyecto proyecto, Usuario usuario, Rol rol) {
       this.id = id;
       this.proyecto = proyecto;
       this.usuario = usuario;
       this.rol = rol;
    }
   
    public ProyectoUsuarioRolId getId() {
        return this.id;
    }
    
    public void setId(ProyectoUsuarioRolId id) {
        this.id = id;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


