package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer proyId;
     private EstadoProyecto estadoProyecto;
     private Cliente cliente;
     private String descProyecto;
     private Set<CasoSoporte> casoSoportes = new HashSet<CasoSoporte>(0);
     private Set<ProyectoUsuarioRol> proyectoUsuarioRols = new HashSet<ProyectoUsuarioRol>(0);
     private Set<Requerimiento> requerimientos = new HashSet<Requerimiento>(0);

    public Proyecto() {
    }

	
    public Proyecto(Integer proyId, EstadoProyecto estadoProyecto, Cliente cliente, String descProyecto) {
        this.proyId = proyId;
        this.estadoProyecto = estadoProyecto;
        this.cliente = cliente;
        this.descProyecto = descProyecto;
    }
    public Proyecto(Integer proyId, EstadoProyecto estadoProyecto, Cliente cliente, String descProyecto, Set<CasoSoporte> casoSoportes, Set<ProyectoUsuarioRol> proyectoUsuarioRols, Set<Requerimiento> requerimientos) {
       this.proyId = proyId;
       this.estadoProyecto = estadoProyecto;
       this.cliente = cliente;
       this.descProyecto = descProyecto;
       this.casoSoportes = casoSoportes;
       this.proyectoUsuarioRols = proyectoUsuarioRols;
       this.requerimientos = requerimientos;
    }
   
    public Integer getProyId() {
        return this.proyId;
    }
    
    public void setProyId(Integer proyId) {
        this.proyId = proyId;
    }
    public EstadoProyecto getEstadoProyecto() {
        return this.estadoProyecto;
    }
    
    public void setEstadoProyecto(EstadoProyecto estadoProyecto) {
        this.estadoProyecto = estadoProyecto;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getDescProyecto() {
        return this.descProyecto;
    }
    
    public void setDescProyecto(String descProyecto) {
        this.descProyecto = descProyecto;
    }
    public Set<CasoSoporte> getCasoSoportes() {
        return this.casoSoportes;
    }
    
    public void setCasoSoportes(Set<CasoSoporte> casoSoportes) {
        this.casoSoportes = casoSoportes;
    }
    public Set<ProyectoUsuarioRol> getProyectoUsuarioRols() {
        return this.proyectoUsuarioRols;
    }
    
    public void setProyectoUsuarioRols(Set<ProyectoUsuarioRol> proyectoUsuarioRols) {
        this.proyectoUsuarioRols = proyectoUsuarioRols;
    }
    public Set<Requerimiento> getRequerimientos() {
        return this.requerimientos;
    }
    
    public void setRequerimientos(Set<Requerimiento> requerimientos) {
        this.requerimientos = requerimientos;
    }




}


