package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer rolId;
     private String descRol;
     private String nombreCorto;
     private Set<ProyectoUsuarioRol> proyectoUsuarioRols = new HashSet<ProyectoUsuarioRol>(0);

    public Rol() {
    }

	
    public Rol(Integer rolId, String descRol, String nombreCorto) {
        this.rolId = rolId;
        this.descRol = descRol;
        this.nombreCorto = nombreCorto;
    }
    public Rol(Integer rolId, String descRol, String nombreCorto, Set<ProyectoUsuarioRol> proyectoUsuarioRols) {
       this.rolId = rolId;
       this.descRol = descRol;
       this.nombreCorto = nombreCorto;
       this.proyectoUsuarioRols = proyectoUsuarioRols;
    }
   
    public Integer getRolId() {
        return this.rolId;
    }
    
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }
    public String getDescRol() {
        return this.descRol;
    }
    
    public void setDescRol(String descRol) {
        this.descRol = descRol;
    }
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    public Set<ProyectoUsuarioRol> getProyectoUsuarioRols() {
        return this.proyectoUsuarioRols;
    }
    
    public void setProyectoUsuarioRols(Set<ProyectoUsuarioRol> proyectoUsuarioRols) {
        this.proyectoUsuarioRols = proyectoUsuarioRols;
    }




}


