package com.dsdsoft.sgp.modelo;
// Generated 24/06/2016 11:19:56 PM by Hibernate Tools 4.0.0



/**
 * SeguimientoCaso generated by hbm2java
 */
public class SeguimientoCaso  implements java.io.Serializable {


     private Integer secaId;
     private CasoSoporte casoSoporte;
     private Usuario usuario;
     private String descripcionActividad;

    public SeguimientoCaso() {
    }

    public SeguimientoCaso(Integer secaId, CasoSoporte casoSoporte, Usuario usuario, String descripcionActividad) {
       this.secaId = secaId;
       this.casoSoporte = casoSoporte;
       this.usuario = usuario;
       this.descripcionActividad = descripcionActividad;
    }
   
    public Integer getSecaId() {
        return this.secaId;
    }
    
    public void setSecaId(Integer secaId) {
        this.secaId = secaId;
    }
    public CasoSoporte getCasoSoporte() {
        return this.casoSoporte;
    }
    
    public void setCasoSoporte(CasoSoporte casoSoporte) {
        this.casoSoporte = casoSoporte;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcionActividad() {
        return this.descripcionActividad;
    }
    
    public void setDescripcionActividad(String descripcionActividad) {
        this.descripcionActividad = descripcionActividad;
    }




}


